import type { Structure, ModuleId, CataractType } from './types';

export const sources = [
  { id: 'gross', title: 'Gross Anatomy of the Eye', author: 'Webvision · NCBI Bookshelf', url: 'https://www.ncbi.nlm.nih.gov/books/NBK11534/', scope: 'Hubungan spasial, tunika, dan bilik mata.' },
  { id: 'neuro', title: 'Anatomy of the Eye', author: 'Neuroscience · NCBI Bookshelf', url: 'https://www.ncbi.nlm.nih.gov/books/NBK11120/', scope: 'Struktur optik, retina, dan saraf optik.' },
  { id: 'aqueous', title: 'Aqueous Humor Dynamics: A Review', author: 'Goel et al. · 2010', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3032230/', scope: 'Sekresi, sirkulasi, dan resistensi aliran aqueous.' },
  { id: 'outflow', title: 'Unconventional Aqueous Humor Outflow: A Review', author: 'Johnson et al. · 2017', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC4970980/', scope: 'Jalur uveoskleral dan variasi proporsi alirannya.' },
  { id: 'cataract', title: 'Cataract Surgery', author: 'StatPearls · NCBI Bookshelf', url: 'https://www.ncbi.nlm.nih.gov/books/NBK559253/', scope: 'Tipe katarak, perubahan lensa, dan temuan klinis.' },
  { id: 'lensglaucoma', title: 'Lens-Induced Glaucoma: subtype comparison', author: 'StatPearls · NCBI Bookshelf', url: 'https://www.ncbi.nlm.nih.gov/books/NBK574524/table/article-140081.table4/', scope: 'Perbedaan glaukoma fakomorfik dan fakolitik.' },
];

export const structures: Structure[] = [
  {id:'sclera',name:'Sklera',latin:'Sclera',group:'Dinding bola mata',color:'#c4d4dd',description:'Selubung fibrosa yang membentuk sebagian besar dinding luar bola mata.',function:'Mempertahankan bentuk globe dan menjadi tempat perlekatan otot ekstraokular.',relation:'Berlanjut sebagai kornea pada limbus; koroid terletak di sisi dalamnya.',clinical:'Skleritis dapat menimbulkan nyeri dalam yang berat. Sklera berbeda dari konjungtiva yang menutupinya.',fact:'Tunika fibrosa',sources:['gross']},
  {id:'choroid',name:'Koroid',latin:'Choroidea',group:'Dinding bola mata',color:'#b8654d',description:'Lapisan vaskular dan berpigmen di antara sklera dan retina.',function:'Mendukung kebutuhan metabolik retina luar, terutama fotoreseptor.',relation:'Di anterior, uvea berlanjut ke badan siliaris dan iris.',clinical:'Perubahan vaskular koroid dapat mengganggu retina luar dan penglihatan sentral.',fact:'Bagian posterior uvea',sources:['gross','neuro']},
  {id:'retina',name:'Retina',latin:'Retina',group:'Dinding bola mata',color:'#efa078',description:'Jaringan saraf berlapis yang melapisi permukaan dalam bagian posterior bola mata.',function:'Fotoreseptor mengubah cahaya menjadi sinyal saraf; sel ganglion meneruskannya ke otak.',relation:'Berakhir di ora serrata. Akson sel ganglion berkumpul pada diskus optikus.',clinical:'Ablasio retina memisahkan retina neurosensorik dari epitel pigmennya.',fact:'Awal transduksi visual',sources:['neuro']},
  {id:'cornea',name:'Kornea',latin:'Cornea',group:'Segmen anterior',color:'#96d9e0',description:'Permukaan anterior transparan, avaskular, dan melengkung.',function:'Membiaskan cahaya dan melindungi mata. Transparansi memerlukan keteraturan stroma serta pengaturan hidrasi.',relation:'Membatasi bilik anterior di depan dan bertemu sklera di limbus.',clinical:'Edema kornea mengurangi transparansi dan dapat menghasilkan halo.',fact:'Permukaan refraksi utama',sources:['neuro']},
  {id:'iris',name:'Iris',latin:'Iris',group:'Segmen anterior',color:'#78b6a8',description:'Diafragma berpigmen dengan lubang sentral berupa pupil.',function:'Mengatur jumlah cahaya masuk melalui sfingter dan dilator pupil.',relation:'Memisahkan bilik anterior dan posterior; pupil menghubungkan keduanya.',clinical:'Iris perifer yang menutup sudut dapat menghambat akses ke trabecular meshwork.',fact:'Pupil adalah lubang, bukan jaringan',sources:['gross','aqueous']},
  {id:'lens',name:'Lensa kristalin',latin:'Lens crystallina',group:'Segmen anterior',color:'#f1ce8c',description:'Struktur transparan bikonveks di belakang iris, ditahan oleh serabut zonula.',function:'Memfokuskan cahaya ke retina dan mengubah daya bias saat akomodasi.',relation:'Permukaan anterior berdekatan dengan iris; permukaan posterior berbatasan dengan vitreus.',clinical:'Opasifikasi lensa disebut katarak. Lokasi opasitas memengaruhi keluhan dan temuan pemeriksaan.',fact:'Avaskular · bikonveks',sources:['gross','cataract']},
  {id:'ciliary',name:'Badan siliaris',latin:'Corpus ciliare',group:'Segmen anterior',color:'#d18d92',description:'Bagian uvea dengan otot siliaris serta prosesus siliaris.',function:'Epitel nonpigmen menyekresi aqueous; kontraksi otot siliaris mengurangi tegangan zonula untuk akomodasi dekat.',relation:'Terletak di belakang akar iris dan berlanjut ke koroid.',clinical:'Produksi aqueous merupakan salah satu sasaran terapi penurunan tekanan intraokular.',fact:'Sekresi + akomodasi',sources:['aqueous','gross']},
  {id:'zonules',name:'Serabut zonula',latin:'Zonula ciliaris',group:'Segmen anterior',color:'#e4d8b0',description:'Serabut suspensorium yang menghubungkan badan siliaris dengan kapsul lensa.',function:'Mentransmisikan tegangan untuk mempertahankan posisi dan membantu perubahan bentuk lensa.',relation:'Melekat di sekitar ekuator lensa, di belakang iris.',clinical:'Kelemahan zonula dapat menyebabkan subluksasi lensa.',fact:'Penghubung badan siliaris–lensa',sources:['gross']},
  {id:'anterior',name:'Bilik anterior',latin:'Camera anterior bulbi',group:'Cairan & drainase',color:'#67d5db',description:'Ruang berisi aqueous humor antara permukaan posterior kornea dan permukaan anterior iris.',function:'Menjadi lintasan aqueous menuju sudut iridokorneal.',relation:'Berhubungan dengan bilik posterior melalui pupil.',clinical:'Kedalaman bilik dan konfigurasi sudut relevan pada mekanisme penutupan sudut.',fact:'Di depan iris',sources:['gross','aqueous']},
  {id:'posterior',name:'Bilik posterior',latin:'Camera posterior bulbi',group:'Cairan & drainase',color:'#afa8eb',description:'Ruang sempit di belakang iris, di depan lensa dan zonula, dibatasi lateral oleh badan siliaris.',function:'Menerima aqueous yang disekresikan prosesus siliaris sebelum melewati pupil.',relation:'Bukan rongga besar di belakang lensa; rongga tersebut berisi vitreus.',clinical:'Blok pupil menghambat aliran dari bilik posterior ke bilik anterior.',fact:'Di belakang iris ≠ rongga vitreus',sources:['gross','aqueous']},
  {id:'trabecular',name:'Trabecular meshwork',latin:'Reticulum trabeculare',group:'Cairan & drainase',color:'#70dbb3',description:'Jaringan berpori di sudut iridokorneal yang menjadi pintu masuk jalur konvensional.',function:'Mengatur resistensi aliran sebelum aqueous masuk ke kanal Schlemm.',relation:'Terdiri atas bagian uveal, korneoskleral, dan jukstakanalikular.',clinical:'Peningkatan resistensi outflow dapat menaikkan tekanan intraokular walaupun sudut tetap terbuka.',fact:'Jalur konvensional',sources:['aqueous']},
  {id:'schlemm',name:'Kanal Schlemm',latin:'Sinus venosus sclerae',group:'Cairan & drainase',color:'#5ab6cf',description:'Saluran melingkar di limbus, di sebelah luar trabecular meshwork.',function:'Meneruskan aqueous ke kanal kolektor dan sirkulasi vena episklera.',relation:'Dinding dalamnya berbatasan dengan jaringan jukstakanalikular.',clinical:'Tekanan vena episklera ikut memengaruhi tekanan intraokular.',fact:'TM → Schlemm → kanal kolektor',sources:['aqueous']},
  {id:'vitreous',name:'Badan vitreus',latin:'Corpus vitreum',group:'Segmen posterior',color:'#9eafcf',description:'Gel transparan yang mengisi rongga besar di belakang lensa.',function:'Mentransmisikan cahaya dan berinteraksi secara mekanik dengan retina.',relation:'Berbatasan dengan lensa di anterior dan retina di posterior.',clinical:'Traksi vitreoretina dapat menimbulkan robekan retina. Vitreus tidak mengikuti sirkulasi aqueous.',fact:'Gel, bukan aqueous humor',sources:['gross','neuro']},
  {id:'optic',name:'Saraf optik',latin:'Nervus opticus · CN II',group:'Segmen posterior',color:'#e6c6a6',description:'Kumpulan akson sel ganglion retina yang keluar melalui diskus optikus.',function:'Membawa informasi visual menuju jalur penglihatan di otak.',relation:'Diskus terletak nasal terhadap makula dan tidak memiliki fotoreseptor.',clinical:'Glaukoma merupakan neuropati optik; tekanan intraokular saja tidak menetapkan diagnosis.',fact:'Saraf kranial II',sources:['neuro']},
];

export const modules: {id:ModuleId; number:string; title:string; subtitle:string; heading:string}[] = [
  {id:'anatomy',number:'01',title:'Anatomi mata',subtitle:'Struktur & hubungan spasial',heading:'Kenali setiap lapisan.'},
  {id:'aqueous',number:'02',title:'Aqueous humor',subtitle:'Produksi, aliran & drainase',heading:'Ikuti perjalanan aqueous.'},
  {id:'cataract',number:'03',title:'Katarak',subtitle:'Patogenesis & temuan klinis',heading:'Dari lensa jernih ke opasitas.'},
];

export const flowSteps = [
  {title:'Produksi',structure:'ciliary',detail:'Epitel nonpigmen prosesus siliaris menyekresi ion; air mengikuti gradien osmotik. Sekresi aktif adalah mekanisme utama, disertai ultrafiltrasi dan difusi.'},
  {title:'Bilik posterior',structure:'posterior',detail:'Aqueous masuk ke ruang sempit di belakang iris. Perhatikan bahwa alirannya tidak memasuki rongga vitreus.'},
  {title:'Melewati pupil',structure:'iris',detail:'Aqueous mengalir di antara iris dan lensa, lalu melalui pupil menuju bilik anterior.'},
  {title:'Bilik anterior',structure:'anterior',detail:'Aqueous bergerak menuju sudut iridokorneal. Konveksi juga terjadi: naik di sisi iris/lensa yang lebih hangat, turun dekat kornea yang lebih dingin saat tubuh tegak.'},
  {title:'Dua jalur keluar',structure:'trabecular',detail:'Jalur konvensional: TM → kanal Schlemm → kanal kolektor → vena episklera. Jalur uveoskleral: sela otot siliaris → ruang suprakoroid → menembus sklera.'},
] as const;

export const cataracts: Record<CataractType,{name:string;location:string;mechanism:string;findings:string[];pearl:string}> = {
  nuclear:{name:'Nuklear',location:'Nukleus lensa',mechanism:'Perubahan protein kristalin dan pemadatan nukleus menyebabkan penguningan serta peningkatan hamburan cahaya.',findings:['Nukleus menguning hingga kecokelatan','Penglihatan kabur dan warna memudar','Pergeseran miopik dapat terjadi'],pearl:'Pergeseran miopik khas pada sklerosis nuklear; bukan ciri universal semua katarak.'},
  cortical:{name:'Kortikal',location:'Korteks perifer → sentral',mechanism:'Gangguan serabut serta hidrasi korteks menghasilkan celah dan opasitas berbentuk jari-jari dari perifer.',findings:['Opasitas radial menyerupai jari-jari roda','Silau, terutama saat berkendara malam','Gejala bergantung keterlibatan aksis visual'],pearl:'Opasitas kortikal dapat tampak jelas pada retroiluminasi, dengan bagian tengah awalnya relatif jernih.'},
  psc:{name:'Subkapsular posterior',location:'Di depan kapsul posterior',mechanism:'Opasitas granular terbentuk pada korteks posterior, dekat aksis visual dan tepat di anterior kapsul posterior.',findings:['Plak atau granula pada bagian posterior lensa','Silau dan kesulitan membaca','Dapat lebih mengganggu saat pupil mengecil'],pearl:'Lokasinya dekat aksis visual: opasitas yang kecil dapat menimbulkan keluhan yang bermakna.'},
};

export function illustrativeIOP(production:number,facility:number,uveoscleral:number,episcleral=9){
  return (production-uveoscleral)/facility+episcleral;
}
