import type { Structure, ModuleId, CataractType } from './types';
import {orbitalStructures} from './orbitContent.ts';

export const sources = [
  {id:'orbit-anatomy',title:'Anatomy, Head and Neck, Orbit',author:'StatPearls · NCBI Bookshelf',url:'https://www.ncbi.nlm.nih.gov/books/NBK539843/',scope:'Orbita, selubung, kelopak, dan hubungan struktur; bentuk 3D adalah rekonstruksi skematik.'},
  {id:'eom-anatomy',title:'Anatomy, Head and Neck, Eye Extraocular Muscles',author:'StatPearls · NCBI Bookshelf',url:'https://www.ncbi.nlm.nih.gov/books/NBK519565/',scope:'Asal, insersi, arah otot, serta inervasi otot ekstraokular.'},
  {id:'lacrimal-anatomy',title:'Anatomy, Head and Neck: Eye Lacrimal Gland',author:'StatPearls · NCBI Bookshelf',url:'https://www.ncbi.nlm.nih.gov/books/NBK532914/',scope:'Kelenjar lakrimal dan hubungan dengan permukaan mata.'},
  {id:'lacrimal-drainage',title:'Anatomy, Head and Neck: Eye Nasolacrimal',author:'StatPearls · NCBI Bookshelf',url:'https://www.ncbi.nlm.nih.gov/books/NBK482213/',scope:'Puncta, kanalikuli, sakus, dan duktus nasolakrimal menuju meatus inferior.'},
  {id:'biometry-variation',title:'The Effect of Age, Accommodation and Refractive Error on the Adult Human Eye',author:'Richdale et al. · Optometry and Vision Science · 2016',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC4692191/',scope:'Arah perubahan dimensi terkait usia. Preset dan koefisien morph pada atlas adalah ilustrasi, bukan model regresi penelitian.'},
  { id: 'gross', title: 'Gross Anatomy of the Eye', author: 'Webvision · NCBI Bookshelf', url: 'https://www.ncbi.nlm.nih.gov/books/NBK11534/', scope: 'Hubungan spasial, tunika, dan bilik mata.' },
  { id: 'neuro', title: 'Anatomy of the Eye', author: 'Neuroscience · NCBI Bookshelf', url: 'https://www.ncbi.nlm.nih.gov/books/NBK11120/', scope: 'Struktur optik, retina, dan saraf optik.' },
  { id: 'aqueous', title: 'Aqueous Humor Dynamics: A Review', author: 'Goel et al. · 2010', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3032230/', scope: 'Sekresi, sirkulasi, dan resistensi aliran aqueous.' },
  { id: 'outflow', title: 'Unconventional Aqueous Humor Outflow: A Review', author: 'Johnson et al. · 2017', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC4970980/', scope: 'Jalur uveoskleral dan variasi proporsi alirannya.' },
  { id: 'cataract', title: 'Cataract Surgery', author: 'StatPearls · NCBI Bookshelf', url: 'https://www.ncbi.nlm.nih.gov/books/NBK559253/', scope: 'Tipe katarak, perubahan lensa, dan temuan klinis.' },
  { id: 'lensglaucoma', title: 'Lens-Induced Glaucoma: subtype comparison', author: 'StatPearls · NCBI Bookshelf', url: 'https://www.ncbi.nlm.nih.gov/books/NBK574524/table/article-140081.table4/', scope: 'Perbedaan glaukoma fakomorfik dan fakolitik.' },
  { id: 'cornea-tx', title: 'Cornea Transplantation', author: 'StatPearls · NCBI Bookshelf', url: 'https://www.ncbi.nlm.nih.gov/books/NBK539690/', scope: 'Lima lapis kornea, ketebalan, dan peran tiap lapis.' },
  { id: 'aao-cornea', title: 'Five layers of the cornea', author: 'American Academy of Ophthalmology', url: 'https://www.aao.org/education/image/five-layers-of-cornea-1', scope: 'Ketebalan histologis tiap lapis kornea.' },
  { id: 'angle-outflow', title: 'Aqueous outflow: TM to episcleral veins', author: 'PMC reviews · outflow continuum', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC5350024/', scope: 'TM tiga zona, kanal Schlemm, kolektor, dan resistensi JCT.' },
  { id: 'gonio', title: 'Gonioscopy and angle closure', author: 'WesternU · after Alward atlas', url: 'https://ce-optometry.westernu.edu/bin/pdf/regular-course/handout_gonioscopy.pdf', scope: 'Urutan struktur sudut dan grading Shaffer/Spaeth/van Herick.' },
  { id: 'lens-structure', title: 'Structure of the lens and its associations with visual quality', author: 'PMC · lens review', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC7511618/', scope: 'Kapsul, epitel, serabut, sutura Y, dan akomodasi Helmholtz.' },
  { id: 'zonule', title: "Zinn's Zonule", author: 'Bassnett · 2020 · PMC', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC8139560/', scope: 'Serabut fibrilin, tine anterior/posterior/ekuatorial, dan unit akomodasi.' },
  { id: 'ciliary-epi', title: 'Ciliary Body and Ciliary Epithelium', author: 'PMC · ciliary review', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3018825/', scope: 'Pars plicata/plana, otot siliaris, dan bilayer pigmen-nonpigmen.' },
  { id: 'iris-sphincter', title: 'Anatomy: Eye Iris Sphincter Muscle', author: 'StatPearls · NCBI Bookshelf', url: 'https://www.ncbi.nlm.nih.gov/books/NBK532252/', scope: 'Sfingter/dilator pupil dan persarafannya.' },
  { id: 'webvision', title: 'Webvision: Organization of the Retina', author: 'Univ. of Utah · Webvision', url: 'https://www.webvision.pitt.edu/', scope: 'Lapisan retina, sirkuit, dan fotoreseptor.' },
  { id: 'aveh-retina', title: 'Review: human retina, nerve fibre layer and macula', author: 'Mashige · Afr Vision Eye Health', url: 'https://avehjournal.org/index.php/aveh/article/view/330/495', scope: '10 lapis, makula/fovea, diskus, ora serrata, ketebalan regional.' },
  { id: 'lamina', title: 'Lamina Cribrosa in Glaucoma', author: 'PMC · review', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC4455897/', scope: 'Lamina kribrosa, defek fokal, dan cupping glaukomatosa.' },
  { id: 'cn2', title: 'Neuroanatomy, Cranial Nerve 2 (Optic)', author: 'StatPearls · NCBI Bookshelf', url: 'https://www.ncbi.nlm.nih.gov/books/NBK507907/', scope: 'Akson RGC, lamina, mielinisasi, dan blind spot.' },
  { id: 'cm-ubm', title: 'Ciliary muscle morphology with accommodation and ametropia', author: 'IOVS · ARVO', url: 'https://iovs.arvojournals.org/article.aspx?articleid=2127601', scope: 'Geser anterior + sentripetal massa otot saat akomodasi.' },
  { id: 'cm-age', title: 'Effect of age, accommodation and refractive error on the adult eye', author: 'PMC · OCT biometry', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC4692191/', scope: 'Ring −0,08 mm/D, ekuator −0,07 mm/D, tebal +0,06 mm/D.' },
  { id: 'cm-choroid', title: 'Accommodative movements of vitreous, choroid, sclera', author: 'Croft et al. · PMC', url: 'https://pmc.ncbi.nlm.nih.gov/articles/PMC3726242/', scope: 'Otot menarik khoroid/retina ke anterior; hialoid melengkung posterior.' },
  { id: 'aao-accomm', title: 'Consolidated accommodation theory (CAMA)', author: 'AAO · Croft/Lütjen-Drecoll', url: 'https://www.aao.org/education/current-insight/new-consolidated-accommodation-theory-may-change-f', scope: 'Zonula resiprokal, ekuator −3,5%, tebal +300 µm.' },
];

export const structures: Structure[] = [
  ...orbitalStructures,
  {id:'sclera',name:'Sklera',latin:'Sclera',group:'Dinding bola mata',color:'#c4d4dd',description:'Selubung fibrosa yang membentuk sebagian besar dinding luar bola mata.',function:'Mempertahankan bentuk globe dan menjadi tempat perlekatan otot ekstraokular.',relation:'Berlanjut sebagai kornea pada limbus; koroid terletak di sisi dalamnya.',clinical:'Skleritis dapat menimbulkan nyeri dalam yang berat. Sklera berbeda dari konjungtiva yang menutupinya.',fact:'Tunika fibrosa',sources:['gross']},
  {id:'choroid',name:'Koroid',latin:'Choroidea',group:'Dinding bola mata',color:'#b8654d',description:'Lapisan vaskular dan berpigmen di antara sklera dan retina.',function:'Mendukung kebutuhan metabolik retina luar, terutama fotoreseptor.',relation:'Di anterior, uvea berlanjut ke badan siliaris dan iris.',clinical:'Perubahan vaskular koroid dapat mengganggu retina luar dan penglihatan sentral.',fact:'Bagian posterior uvea',sources:['gross','neuro']},
  {id:'retina',name:'Retina',latin:'Retina',group:'Dinding bola mata',color:'#efa078',description:'Jaringan saraf berlapis yang melapisi permukaan dalam bagian posterior bola mata.',function:'Fotoreseptor mengubah cahaya menjadi sinyal saraf; sel ganglion meneruskannya ke otak.',relation:'Berakhir di ora serrata. Akson sel ganglion berkumpul pada diskus optikus.',clinical:'Ablasio retina memisahkan retina neurosensorik dari epitel pigmennya.',fact:'Awal transduksi visual',sources:['neuro']},
  {id:'cornea',name:'Kornea',latin:'Cornea',group:'Segmen anterior',color:'#96d9e0',description:'Permukaan anterior transparan, avaskular, dan melengkung.',function:'Membiaskan cahaya dan melindungi mata. Transparansi memerlukan keteraturan stroma serta pengaturan hidrasi.',relation:'Membatasi bilik anterior di depan dan bertemu sklera di limbus.',clinical:'Edema kornea mengurangi transparansi dan dapat menghasilkan halo.',fact:'Permukaan refraksi utama',sources:['neuro']},
  {id:'iris',name:'Iris',latin:'Iris',group:'Segmen anterior',color:'#78b6a8',description:'Diafragma berpigmen dengan lubang sentral berupa pupil.',function:'Mengatur jumlah cahaya masuk melalui sfingter dan dilator pupil.',relation:'Memisahkan bilik anterior dan posterior; pupil menghubungkan keduanya.',clinical:'Iris perifer yang menutup sudut dapat menghambat akses ke trabecular meshwork.',fact:'Pupil adalah lubang, bukan jaringan',sources:['gross','aqueous']},
  {id:'lens',name:'Lensa kristalin',latin:'Lens crystallina',group:'Segmen anterior',color:'#f1ce8c',description:'Struktur transparan bikonveks di belakang iris, ditahan oleh serabut zonula.',function:'Memfokuskan cahaya ke retina dan mengubah daya bias saat akomodasi.',relation:'Permukaan anterior berdekatan dengan iris; permukaan posterior berbatasan dengan vitreus.',clinical:'Opasifikasi lensa disebut katarak. Lokasi opasitas memengaruhi keluhan dan temuan pemeriksaan.',fact:'Avaskular · bikonveks',sources:['gross','cataract']},
  {id:'ciliary',name:'Badan siliaris',latin:'Corpus ciliare',group:'Segmen anterior',color:'#d18d92',description:'Bagian uvea dengan otot siliaris serta prosesus siliaris.',function:'Epitel nonpigmen menyekresi aqueous; kontraksi otot siliaris mengurangi tegangan zonula untuk akomodasi dekat.',relation:'Terletak di belakang akar iris dan berlanjut ke koroid.',clinical:'Produksi aqueous merupakan salah satu sasaran terapi penurunan tekanan intraokular.',fact:'Sekresi + akomodasi',sources:['aqueous','gross']},
  {id:'zonules',name:'Serabut zonula',latin:'Zonula ciliaris',group:'Segmen anterior',color:'#e4d8b0',description:'Serabut suspensorium yang menghubungkan badan siliaris dengan kapsul lensa.',function:'Mentransmisikan tegangan untuk mempertahankan posisi dan membantu perubahan bentuk lensa.',relation:'Melekat di sekitar ekuator lensa, di belakang iris.',clinical:'Kelemahan zonula dapat menyebabkan subluksasi lensa.',fact:'Penghubung badan siliaris–lensa',sources:['gross']},
  {id:'anterior',name:'Bilik anterior',latin:'Camera anterior bulbi',group:'Cairan & drainase',color:'#67d5db',description:'Ruang berisi aqueous humor antara permukaan posterior kornea dan permukaan anterior iris.',function:'Menjadi lintasan aqueous menuju sudut iridokorneal.',relation:'Berhubungan dengan bilik posterior melalui pupil.',clinical:'Kedalaman bilik dan konfigurasi sudut relevan pada mekanisme penutupan sudut.',fact:'Di depan iris',sources:['gross','aqueous']},
  {id:'posterior',name:'Bilik posterior',latin:'Camera posterior bulbi',group:'Cairan & drainase',color:'#afa8eb',description:'Ruang sempit di belakang iris, di depan lensa dan zonula, dibatasi lateral oleh badan siliaris.',function:'Menerima aqueous yang disekresikan prosesus siliaris sebelum melewati pupil.',relation:'Bukan rongga besar di belakang lensa; rongga tersebut berisi vitreus.',clinical:'Blok pupil menghambat aliran dari bilik posterior ke bilik anterior.',fact:'Di belakang iris ≠ rongga vitreus',sources:['gross','aqueous']},
  {id:'trabecular',name:'Trabecular meshwork',latin:'Reticulum trabeculare',group:'Cairan & drainase',color:'#70dbb3',description:'Jaringan berpori di sudut iridokorneal yang menjadi pintu masuk jalur konvensional.',function:'Mengatur resistensi aliran sebelum aqueous masuk ke kanal Schlemm.',relation:'Terdiri atas bagian uveal, korneoskleral, dan jukstakanalikular.',clinical:'Peningkatan resistensi outflow dapat menaikkan tekanan intraokular walaupun sudut tetap terbuka.',fact:'Jalur konvensional',sources:['aqueous']},
  {id:'schlemm',name:'Kanal Schlemm',latin:'Sinus venosus sclerae',group:'Cairan & drainase',color:'#5ab6cf',description:'Saluran melingkar di limbus, di sebelah luar trabecular meshwork.',function:'Meneruskan aqueous ke kanal kolektor dan sirkulasi vena episklera.',relation:'Dinding dalamnya berbatasan dengan jaringan jukstakanalikular.',clinical:'Tekanan vena episklera ikut memengaruhi tekanan intraokular.',fact:'TM → Schlemm → kanal kolektor',sources:['aqueous']},
  {id:'vitreous',name:'Badan vitreus',latin:'Corpus vitreum',group:'Segmen posterior',color:'#9eafcf',description:'Gel transparan yang mengisi rongga besar di belakang lensa.',function:'Mentransmisikan cahaya dan berinteraksi secara mekanik dengan retina.',relation:'Berbatasan dengan lensa di anterior dan retina di posterior.',clinical:'Traksi vitreoretina dapat menimbulkan robekan retina. Vitreus tidak mengikuti sirkulasi aqueous.',fact:'Gel, bukan aqueous humor',sources:['gross','neuro']},
  {id:'optic',name:'Saraf optik',latin:'Nervus opticus · CN II',group:'Segmen posterior',color:'#e6c6a6',description:'Kumpulan akson sel ganglion retina yang keluar melalui diskus optikus.',function:'Membawa informasi visual menuju jalur penglihatan di otak.',relation:'Diskus terletak nasal terhadap makula dan tidak memiliki fotoreseptor.',clinical:'Glaukoma merupakan neuropati optik; tekanan intraokular saja tidak menetapkan diagnosis.',fact:'Saraf kranial II',sources:['neuro']},
];

export const modules: {id:ModuleId; number:string; title:string; subtitle:string; heading:string}[] = [
  {id:'anatomy',number:'01',title:'Anatomi mata',subtitle:'Struktur & hubungan spasial',heading:'Kenali setiap lapisan.'},
  {id:'aqueous',number:'02',title:'Aqueous humor',subtitle:'Produksi, aliran & drainase',heading:'Ikuti perjalanan aqueous.'},
  {id:'cataract',number:'03',title:'Katarak',subtitle:'Patogenesis & temuan klinis',heading:'Dari lensa jernih ke opasitas.'},
];

export const flowSteps = [
  {title:'Produksi',structure:'ciliary',detail:'Epitel nonpigmen prosesus siliaris menyekresi ion; air mengikuti gradien osmotik. Sekresi aktif adalah mekanisme utama, disertai ultrafiltrasi dan difusi.'},
  {title:'Bilik posterior',structure:'posterior',detail:'Aqueous masuk ke ruang sempit di belakang iris. Perhatikan bahwa alirannya tidak memasuki rongga vitreus.'},
  {title:'Melewati pupil',structure:'iris',detail:'Aqueous mengalir di antara iris dan lensa, lalu melalui pupil menuju bilik anterior.'},
  {title:'Bilik anterior',structure:'anterior',detail:'Aqueous bergerak menuju sudut iridokorneal. Konveksi juga terjadi: naik di sisi iris/lensa yang lebih hangat, turun dekat kornea yang lebih dingin saat tubuh tegak.'},
  {title:'Dua jalur keluar',structure:'trabecular',detail:'Jalur konvensional: TM → kanal Schlemm → kanal kolektor → vena episklera. Jalur uveoskleral: sela otot siliaris → ruang suprakoroid → menembus sklera.'},
] as const;

export const cataracts: Record<CataractType,{name:string;location:string;mechanism:string;findings:string[];pearl:string}> = {
  nuclear:{name:'Nuklear',location:'Nukleus lensa',mechanism:'Perubahan protein kristalin dan pemadatan nukleus menyebabkan penguningan serta peningkatan hamburan cahaya.',findings:['Nukleus menguning hingga kecokelatan','Penglihatan kabur dan warna memudar','Pergeseran miopik dapat terjadi'],pearl:'Pergeseran miopik khas pada sklerosis nuklear; bukan ciri universal semua katarak.'},
  cortical:{name:'Kortikal',location:'Korteks perifer → sentral',mechanism:'Gangguan serabut serta hidrasi korteks menghasilkan celah dan opasitas berbentuk jari-jari dari perifer.',findings:['Opasitas radial menyerupai jari-jari roda','Silau, terutama saat berkendara malam','Gejala bergantung keterlibatan aksis visual'],pearl:'Opasitas kortikal dapat tampak jelas pada retroiluminasi, dengan bagian tengah awalnya relatif jernih.'},
  psc:{name:'Subkapsular posterior',location:'Di depan kapsul posterior',mechanism:'Opasitas granular terbentuk pada korteks posterior, dekat aksis visual dan tepat di anterior kapsul posterior.',findings:['Plak atau granula pada bagian posterior lensa','Silau dan kesulitan membaca','Dapat lebih mengganggu saat pupil mengecil'],pearl:'Lokasinya dekat aksis visual: opasitas yang kecil dapat menimbulkan keluhan yang bermakna.'},
};

import { evaluateAqueous } from '../../lib/domain/simulation/aqueous.ts';

export function illustrativeIOP(production:number,facility:number,uveoscleral:number,episcleral=9){
  const r=evaluateAqueous({F:production,C:facility,U:uveoscleral,Pv:episcleral});
  return r.ok?r.state.IOP:NaN;
}

// Neraca aliran keadaan tunak (Goldmann termodifikasi, ilustratif):
// F masuk = Qkonv + Quv keluar; Qkonv pressure-dependent, Quv tidak.
// Faktor malam hari ilustratif: produksi dan uveoskleral ikut turun nokturnal.
export const NIGHT_F = 0.65, NIGHT_U = 0.6;
export function applyLighting(production:number,uveoscleral:number,lighting:'day'|'night'){
  return lighting==='night'
    ? {production:production*NIGHT_F,uveoscleral:uveoscleral*NIGHT_U}
    : {production,uveoscleral};
}
export function aqueousBalance(production:number,facility:number,uveoscleral:number,episcleral=9){
  const r=evaluateAqueous({F:production,C:facility,U:uveoscleral,Pv:episcleral});
  if(!r.ok)return {iop:NaN,qconv:0,quv:uveoscleral,shareConv:0};
  return {iop:r.state.IOP,qconv:r.state.qConv,quv:r.state.qU,shareConv:r.state.shareConv};
}

// Straylight ilustratif per tipe (Labuz: kortikal +1,05 / nuklear +1,36 /
// PSC +1,54 log(s) pada katarak penuh; diskala linear oleh severity slider).
// scatterK menormalkan kortikal = 1 untuk penyebaran berkas skematik.
export const STRAY_BASE = {cortical:1.05,nuclear:1.36,psc:1.54} as const;
export const SCATTER_K = {cortical:1.0,nuclear:1.25,psc:1.45} as const;
export function straylightGain(type:keyof typeof STRAY_BASE,severity:number){
  return STRAY_BASE[type]*Math.min(100,Math.max(0,severity))/100;
}

export interface MicroLayer {
  id: string; name: string; latin: string; color: string; thickness: string;
  description: string; role: string; clinical: string; sources: string[];
}

export const MICRO_SCALE_NOTE = 'Tampilan detail memakai skala skematik yang diperbesar. Ketebalan, pori, dan kanal diperjelas agar terlihat; bukan ukuran mikrometer sebenarnya dan bukan potongan histologi pasien.';

// Anterior (+X) ke posterior (−X). Urutan dan kisaran ketebalan mengikuti AAO five layers
// dan StatPearls Cornea Transplantation; lapisan Dua dicatat sebagai bidang belah bedah,
// bukan lapis keenam.
export const corneaLayers: MicroLayer[] = [
  { id: 'epithelium', name: 'Epitel', latin: 'Epithelium anterius', color: '#f2c9a0', thickness: '±40–50 µm · 5–7 lapis sentral', description: 'Epitel skuamosa berlapis tanpa keratin: sel basal kolumnar (satu-satunya yang bermitosis), sel wing 2–3 lapis, dan sel skuamosa permukaan. Diperbarui dari limbus ke sentral.', role: 'Barier utama, permukaan optik yang halus, dan fungsi imun. Menyumbang sebagian kecil daya bias lewat kehalusan permukaan.', clinical: 'Defek epitel menimbulkan nyeri dan risiko infeksi; penyembuhan yang buruk mengaburkan permukaan optik.', sources: ['cornea-tx', 'aao-cornea'] },
  { id: 'bowman', name: "Lapisan Bowman", latin: 'Lamina limitans anterior', color: '#e8b4a0', thickness: '±8–15 µm · aseluler', description: 'Kondensasi aseluler stroma anterior dari kolagen tipe I/V yang anyamannya acak. Batas anteriornya tegas di bawah membran basal epitel; batas posteriornya menyatu ke stroma.', role: 'Menjaga bentuk dan kekakuan anterior; bukan membran basal sejati dan tidak beregenerasi sempurna setelah rusak.', clinical: 'Robekan atau jaringan parut di sini (mis. keratokonus lanjut, trauma) sulit pulih mulus dan memengaruhi topografi.', sources: ['cornea-tx', 'aao-cornea'] },
  { id: 'stroma', name: 'Stroma', latin: 'Substantia propria', color: '#a9cfe0', thickness: '±470–500 µm · ~90% · ~200 lamela', description: 'Serabut kolagen teratur dalam lamela, glikosaminoglikan, dan keratosit yang saling terhubung. Keteraturan anterior lebih padat daripada posterior.', role: 'Kekuatan mekanik dan sebagian besar ketebalan; keteraturan fibril + hidrasi terkontrol menjaga transparansi dan sebagian daya bias.', clinical: 'Edema, parut, atau lamela tak teratur menurunkan transparansi dan menimbulkan halo. Target utama keratoplasti lamelar anterior (DALK).', sources: ['cornea-tx', 'aao-cornea'] },
  { id: 'descemet', name: 'Membran Descemet', latin: 'Lamina limitans posterior', color: '#9db8e8', thickness: '±7–12 µm · menebal dengan usia', description: 'Membran basal dari kolagen tipe IV dan laminin yang disekresi terus-menerus oleh endotel. Landasan melekatnya sel endotel.', role: 'Landasan endotel dan barier posterior; elastis dan berkontribusi pada transparansi.', clinical: 'Robekan Descemet (mis. pada keratokonus akut/hidrops) menyebabkan edema stromal mendadak. Bidang belah bedah 10 µm di atasnya kadang disebut lapis Dua/pre-Descemet — varian bedah, bukan lapis keenam yang disepakati.', sources: ['cornea-tx', 'aao-cornea'] },
  { id: 'endothelium', name: 'Endotel', latin: 'Endothelium', color: '#8fd0c2', thickness: '±4–6 µm · selapis · non-mitotik', description: 'Selapis sel poligonal non-mitotik antara kornea dan bilik anterior. Kepadatan menurun dengan usia dan tidak pulih lewat pembelahan biasa.', role: 'Pompa metabolik yang mengatur hidrasi stroma: menjaga kornea tetap relatif dehidrasi agar transparan.', clinical: 'Kegagalan pompa (mis. dekompensasi endotel) → edema kronis dan kabur. Target keratoplasti endotel (DSEK/DSAEK/DMEK).', sources: ['cornea-tx', 'aao-cornea'] },
];

// Posterior→anterior pada gonioskopi dibaca: pita badan siliaris → scleral spur →
// TM posterior berpigmen → TM anterior → garis Schwalbe. Dimensi mengikuti review outflow:
// JCT 2–20 µm (resistensi utama + dinding dalam Schlemm), Schlemm Ø 190–370 µm,
// pori uveal 25–75 µm, korneoskleral 8–15 lamela @5–12 µm.
export const angleStructures: MicroLayer[] = [
  { id: 'schwalbe', name: "Garis Schwalbe", latin: "Linea Schwalbe · akhir Descemet", color: '#cfd8e6', thickness: 'Penanda apeks sudut', description: 'Terminasi perifer membran Descemet/endotel kornea. Pada gonioskopi tampak sebagai garis padat keputihan di anterior TM.', role: 'Batas anterior sudut dan apeks segitiga TM. Walking the slit-lamp beam (corneal wedge) membantu membedakannya dari TM berpigmen.', clinical: 'Posterior embryotoxon = Schwalbe yang menonjol ke anterior (mis. spektrum Axenfeld-Rieger). Jembatan iris ke Schwalbe = sinekia anterior perifer bila menutup sudut.', sources: ['angle-outflow', 'gonio'] },
  { id: 'uveal-tm', name: 'TM uveal', latin: 'Reticulum trabeculare uveale', color: '#7fd6ae', thickness: '1–3 balok · pori ±25–75 µm', description: 'Lapisan paling dalam, seperti tali/kabel yang saling berhubungan acak dari akar iris/badan siliaris ke daerah Schwalbe. Prosesus iris adalah sisa lapisan ini pada sebagian mata.', role: 'Filter kasar pertama; pori terbesar sehingga resistensinya kecil. Menjembatani reses sudut.', clinical: 'Robekan uveal (resesi sudut pasca trauma) membuat spur tampak lebih putih; risiko glaukoma sudut terbuka pasca trauma tetap ada walau sudut tampak terbuka.', sources: ['angle-outflow', 'gonio'] },
  { id: 'corneoscleral-tm', name: 'TM korneoskleral', latin: 'Reticulum trabeculare corneosclerale', color: '#5ecfa4', thickness: '8–15 lamela @ ±5–12 µm', description: 'Lembaran kolagen-elastin berlubang yang tersusun paralel meridional dari garis Schwalbe ke scleral spur. Ruang antartrabekula mengecil ke arah JCT.', role: 'Filter bertingkat; sel TM melapisi tiap lamela dan ikut menjaga kebersihan matriks (self-cleaning).', clinical: 'Penumpukan pigmen, pseudoeksfoliasi, atau darah dapat menyumbat saringan ini pada sudut yang tetap terbuka.', sources: ['angle-outflow', 'gonio'] },
  { id: 'jct', name: 'JCT / kribriform', latin: 'Juxtacanalicular tissue', color: '#4fc39a', thickness: '±2–20 µm · tanpa lamela', description: 'Jaringan ikat longgar kaya matriks terhidrasi di luar lamela terakhir, tepat di dalam dinding dalam Schlemm. Selnya jarang dan berhubungan dengan sel TM dan sel dinding dalam.', role: 'Lokasi utama resistensi outflow konvensional bersama endotel dinding dalam (vakuola raksasa yang pressure-dependent).', clinical: 'Disregulasi matriks/sitoskeleton di sini menaikkan TIO pada glaukoma sudut terbuka primer tanpa kelainan sudut yang kasatmata.', sources: ['angle-outflow'] },
  { id: 'schlemm-detail', name: 'Kanal Schlemm', latin: 'Sinus venosus sclerae', color: '#5ab6cf', thickness: 'Ø ±190–370 µm · sirkular', description: 'Kanal endotel sirkular di limbus, di luar JCT. Dinding dalamnya berpori trans-seluler; dinding luar bermuara ke entrance kanal kolektor.', role: 'Menampung aqueous dari TM lalu meneruskannya ke pleksus sklera dalam → kolektor radial → vena aqueous → vena episklera (pressure-dependent, lantai alir = tekanan vena episklera).', clinical: 'Darah di Schlemm (blood reflux) bisa normal atau tanda tekanan vena episklera naik; obstruksi distal ke kolektor ikut menaikkan TIO.', sources: ['angle-outflow', 'aqueous'] },
  { id: 'collector', name: 'Kanal kolektor', latin: 'Canales collectores', color: '#669ca6', thickness: 'Radial ke permukaan sklera', description: 'Saluran dari dinding luar Schlemm: entrance → pleksus sklera dalam (sejajar Schlemm) → kolektor intrascleral radial → vena aqueous di permukaan.', role: 'Segmen distal outflow; aliran bersifat segmental (ada zona high-flow dan low-flow mengelilingi 360°).', clinical: 'Bedah yang hanya membuka TM bisa gagal bila hambatan dominan ada di distal (kolektor/episklera). Alasan OCT/gonioskopi menilai sampai distal.', sources: ['angle-outflow'] },
  { id: 'spur', name: 'Scleral spur', latin: 'Calcar sclerae', color: '#d9d2bd', thickness: 'Tonjolan sklera paling anterior', description: 'Proyeksi sklera ke anterior tempat insersi TM dan tendon longitudinal otot siliaris. Pada gonioskopi tampak sebagai garis putih padat di posterior TM berpigmen.', role: 'Jangkar mekanik: kontraksi longitudinal siliaris menarik spur ke posterior → ruang TM terbuka → resistensi turun.', clinical: 'Landmark grading: insersi iris di spur (Spaeth C) vs di TM (B) vs di Schwalbe (A) menentukan sempitnya sudut. Lepasnya badan siliaris dari spur = celah siklodialisis.', sources: ['angle-outflow', 'gonio'] },
];

export const ACCOMMODATION_NOTE = 'Geser 0 (jauh) → 100 (dekat): otot siliaris berkontraksi, tegangan zonula kendor, dan lensa membulat karena elastisitas kapsul. Skema kualitatif teori Helmholtz; bukan pengukuran dioptri, usia, atau amplitudo akomodasi pasien.';

// Luar→dalam pada penampang ekuatorial. Kisaran mengikuti review struktur lensa:
// kapsul anterior ±9–14 µm / ekuator ±17–28 µm / posterior ±2–3 µm; korteks air 73–80%
// RI ~1,386; nukleus air ~68% RI ~1,406–1,41; serabut ~1 cm sutura-ke-sutura;
// sutura Y anterior + Y offset posterior; zonula fibrilin 10–12 nm.
export const lensLayers: MicroLayer[] = [
  { id: 'capsule', name: 'Kapsul', latin: 'Capsula lentis', color: '#f4e6c2', thickness: 'Ant ±9–14 µm · ekuator ±17–28 µm · post ±2–3 µm', description: 'Membran basal elastis, jernih, dan aseluler yang menyelubungi seluruh lensa. Disekresi epitel (anterior) dan serabut; zona superfisialnya (lamela zonular) menjadi tempat sisipan zonula.', role: 'Menahan bentuk dan meneruskan tegangan zonula ke massa lensa. Elastisitasnya adalah motor pembulat saat akomodasi ketika zonula kendor.', clinical: 'Robekan kapsul (trauma/bedah) mengganggu stabilitas lensa. Pada operasi katarak, kapsul posterior dipertahankan sebagai tempat dudukan lensa tanam.', sources: ['lens-structure', 'cataract'] },
  { id: 'lens-epithelium', name: 'Epitel anterior', latin: 'Epithelium anterius lentis', color: '#e8b06a', thickness: 'Selapis kuboid · hanya anterior', description: 'Selapis sel kuboid di antara kapsul anterior dan serabut. Di bow ekuator sel-selnya memanjang menjadi serabut baru — proses yang berlanjut seumur hidup sehingga lensa terus tumbuh dan memadat.', role: 'Homeostasis lensa (transport nutrisi, pompa) dan satu-satunya sumber serabut baru.', clinical: 'Sel sisa yang tertinggal pasca-operasi dapat berproliferasi di kapsul → opasifikasi kapsul posterior (katarak sekunder).', sources: ['lens-structure'] },
  { id: 'cortex', name: 'Korteks', latin: 'Cortex lentis', color: '#f0dcae', thickness: 'Serabut muda · air 73–80% · RI ~1,386', description: 'Lapisan serabut termuda di bawah epitel/kapsul. Serabutnya masih berinti di tepi (bow) dan makin dalam makin kehilangan organel.', role: 'Bagian paling lentur dari massa lensa; deformasinya saat akomodasi terutama berasal dari sini bersama kapsul.', clinical: 'Gangguan hidrasi serabut korteks → celah dan opasitas radial katarak kortikal dari perifer.', sources: ['lens-structure', 'cataract'] },
  { id: 'nucleus', name: 'Nukleus', latin: 'Nucleus lentis', color: '#d9a84e', thickness: 'Embrionik/fetal/dewasa · air ~68% · RI ~1,406–1,41', description: 'Serabut tertua yang terkondensasi di pusat: nukleus embrionik (serabut primer) dikelilingi nukleus fetal lalu dewasa. Serabut matang tanpa inti dan organel.', role: 'Inti indeks bias bertingkat (GRIN): indeks naik ke pusat sehingga daya bias besar tanpa permukaan yang terlalu cembung.', clinical: 'Sklerosis nuklear → penguningan-kecokelatan, hamburan cahaya, dan pergeseran miopik khas.', sources: ['lens-structure', 'cataract'] },
  { id: 'lens-fibers', name: 'Serabut lensa', latin: 'Fibrae lentis', color: '#e5cf9e', thickness: 'Heksagonal · ~1 cm sutura-ke-sutura', description: 'Sel sangat memanjang berpenampang heksagonal, tersusun seperti lapisan bawang dari ekuator ke kutub. Ujung apikal menyusur epitel anterior, ujung basal menyusur kapsul posterior.', role: 'Massa transparan utama; keteraturan susunan + minim organel menjaga kejernihan.', clinical: 'Gangguan diferensiasi serabut (mis. pada bow ekuator) menjadi dasar kekeruhan kortikal dan nuklear.', sources: ['lens-structure'] },
  { id: 'lens-suture', name: 'Sutura Y', latin: 'Sutura lentis', color: '#c9a24e', thickness: 'Y anterior + Y offset posterior', description: 'Garis pertemuan ujung-ujung serabut dari sisi berlawanan: pola Y tegak di anterior dan Y terputar (offset) di posterior, terbentuk sejak pertumbuhan janin.', role: 'Penanda arsitektur pertumbuhan; kompleksitas pola sutura bertambah dengan penambahan lapisan serabut.', clinical: 'Sutura adalah jahitan serabut alami — jangan disamakan dengan jahitan bedah. Kekeruhan dini kadang tampak di sekitar sutura posterior.', sources: ['lens-structure'] },
  { id: 'zonule-attach', name: 'Perlekatan zonula', latin: 'Zonula ciliaris (Zinn)', color: '#dfd3ad', thickness: 'Fibrilin 10–12 nm · 3 tine', description: 'Sistem serabut ekstraseluler transparan dari epitel nonpigmen daerah pars plana: tine anterior dan posterior menambat kapsul ekuator, sebagian berkas langsung ke ekuator, plus berkas terkait vitreus sebagai peredam.', role: 'Mensentrasikan lensa di sumbu visual dan meneruskan gaya otot siliaris. Lensa–zonula–siliaris–vitreus bekerja sebagai satu unit saat akomodasi.', clinical: 'Kelemahan zonula (trauma, pseudoeksfoliasi, Marfan) → subluksasi/luksasi lensa. Tanda intraoperatif: kerut kapsul anterior, rotasi sulit, kantung tidak stabil. Long anterior zonule trait dikaitkan dengan risiko TIO lebih tinggi.', sources: ['zonule', 'lens-structure'] },
];

// Anterior→posterior pada iris, lalu anterior→posterior pada badan siliaris.
// Sfingter = cincin peripupil ±0,75–1 mm (parasimpatis); dilator = radial (simpatis).
// Siliaris 6–7 mm: pars plicata berlipat (70–100 prosesus, vaskular) + pars plana
// halus ±4 mm (relatif avaskular); bilayer PE luar + NPE dalam (sekresi).
export const irisCiliaryStructures: MicroLayer[] = [
  { id: 'sphincter', name: 'Sfingter pupil', latin: 'M. sphincter pupillae', color: '#7fb894', thickness: 'Cincin peripupil ±0,75–1 mm', description: 'Otot polos asal neuroektoderm (optic cup) berbentuk cincin di stroma iris dekat margin pupil, sedikit anterior dari epitel pigmen iris. Zona overlap dengan dilator (collarette) adalah bagian iris paling tebal.', role: 'Miosis: mengecilkan pupil pada cahaya terang lewat refleks cahaya dan saat akomodasi. Dipersarafi parasimpatis CN III (nukleus Edinger-Westphal → ganglion siliaris → saraf siliaris pendek).', clinical: 'Blok parasimpatis (mis. atropin) → midriasis dan lumpuh akomodasi. Lesi eferen pupil → pupil tidak reaktif mengecil.', sources: ['iris-sphincter'] },
  { id: 'dilator', name: 'Dilator pupil', latin: 'M. dilatator pupillae', color: '#a8c69a', thickness: 'Radial · mioepitel posterior', description: 'Lembaran mioepitel radial di permukaan posterior iris dari collarette ke akar iris. Relaksasi sfingter + kontraksi dilator membuka pupil.', role: 'Midriasis pada gelap/stres (fight-or-flight). Dipersarafi simpatis (ganglion servikal superior → saraf siliaris panjang).', clinical: 'Sindrom Horner (lesi simpatis) → miosis + ptosis + anhidrosis. Obat midriatik bekerja lewat jalur ini atau dengan menghambat sfingter.', sources: ['iris-sphincter'] },
  { id: 'ciliary-muscle', name: 'Otot siliaris', latin: 'M. ciliaris', color: '#b07278', thickness: 'Longitudinal + sirkular', description: 'Cincin otot polos di basis badan siliaris. Serabut longitudinal berinsersi ke scleral spur dan prosesus (menarik spur ke posterior); serabut sirkular mengelilingi akar iris dan menggerakkan kompleks siliaris ke anterior-sentripetal.', role: 'Ganda: kontraksi longitudinal membuka ruang TM (outflow naik); kontraksi sirkular mengendurkan zonula (akomodasi dekat). Dipersarafi parasimpatis seperti sfingter.', clinical: 'Pilokarpin (agonis kolinergik) menarik spur → outflow konvensional naik, sekaligus memicu miosis dan pergeseran miopik sementara.', sources: ['ciliary-epi', 'angle-outflow'] },
  { id: 'pars-plicata', name: 'Pars plicata', latin: 'Pars plicata corporis ciliaris', color: '#c89190', thickness: 'Anterior ±2 mm · berlipat', description: 'Zona anterior badan siliaris yang permukaannya berlipat-lipat radial. Setiap lipatan adalah prosesus; lembahnya ikut dilapisi epitel bilayer.', role: 'Memperluas permukaan sekresi aqueous berkali-kali lipat dibanding permukaan datar.', clinical: 'Jaringan target prosedur siklodekstruktif (menurunkan produksi aqueous pada glaukoma refrakter) — dengan risiko inflamasi dan hipoton.', sources: ['ciliary-epi'] },
  { id: 'ciliary-process', name: 'Prosesus siliaris', latin: 'Processus ciliares', color: '#d8a0a4', thickness: '70–100 rigi radial · vaskular', description: 'Rigi-rigi radial menunjuk ke arah pupil dengan stroma kaya pembuluh. Epitel nonpigmen di puncaknya adalah tempat sekresi aktif ion (air mengikuti osmotik); ultrafiltrasi dan difusi menyertai.', role: 'Pabrik aqueous humor sekaligus jangkar anterior zonula pada membran basal epitelnya.', clinical: 'Peradangan di sini (siklisitis) mengganggu produksi aqueous dan sawar darah-aqueous → flare dan sel di bilik anterior.', sources: ['ciliary-epi', 'aqueous'] },
  { id: 'pars-plana', name: 'Pars plana', latin: 'Pars plana (orbiculus ciliaris)', color: '#b99a90', thickness: 'Posterior ±4 mm · halus', description: 'Zona datar relatif avaskular dari akhir prosesus sampai ora serrata. Subepitelnya lebih tebal daripada pars plicata; hampir tanpa fungsi sekretorik pasca-fetal.', role: 'Jendela bedah segmen posterior: minim pembuluh dan tidak ada retina neurosensorik di atasnya.', clinical: 'Port vitrektomi pars plana standar: cukup posterior dari limbus (±3–4 mm, tergantung status lensa) agar tidak melukai lensa maupun retina.', sources: ['ciliary-epi'] },
  { id: 'pe', name: 'Epitel pigmen', latin: 'Epithelium pigmentosum', color: '#5a3a34', thickness: 'Lapis luar bilayer', description: 'Separuh luar bilayer epitel siliaris: sel bergranul melanin asal neuroektoderm, berkesinambungan dengan RPE di ora serrata. Terkopel gap junction ke NPE.', role: 'Barier dan penopang metabolik bagi NPE; menyerap cahaya nyasar di dinding bola mata.', clinical: 'Dispersi pigmen dari gesekan iris-zonula (mis. sindrom dispersi pigmen) dapat menimbun TM dan menaikkan TIO.', sources: ['ciliary-epi'] },
  { id: 'npe', name: 'Epitel nonpigmen', latin: 'Epithelium nonpigmentosum', color: '#e0bc9e', thickness: 'Lapis dalam · sekretorik', description: 'Separuh dalam bilayer: sel besar asal retina neural dengan mitokondria melimpah (aktivitas metabolik tinggi). Bersama endotel kapiler iris membentuk sawar darah-aqueous.', role: 'Sekresi aktif aqueous humor — sasaran utama obat penekan produksi (beta-blocker, inhibitor karbonik anhidrase, agonis alfa-2).', clinical: 'Obat tetes penekan produksi bekerja di sini; keberhasilannya tidak terlihat sebagai perubahan anatomi, melainkan penurunan F pada persamaan Goldmann.', sources: ['ciliary-epi', 'aqueous'] },
];

// Vitreal (+X) ke skleral (−X): 10 lapis neurosensorik + RPE + Bruch, lalu landmark
// fovea dan ora serrata. Ketebalan regional: ±0,56 dekat diskus, 0,35 makula,
// 0,18 ekuator, 0,10 ora, 0,09 fovea. Sirkulasi ganda: khoroid menopang luar
// sampai INL tengah; retinal sentral menopang dalam sampai INL.
export const retinaLayers: MicroLayer[] = [
  { id: 'ilm', name: 'Membran limitan interna', latin: 'Membrana limitans interna', color: '#cfe3ee', thickness: '±2,5 µm · kaki Müller', description: 'Membran basal kaki sel Müller di antarmuka vitreus–retina; berkesinambungan dengan limitan interna badan siliaris. Basis vitreus (lebar 3–4 mm mengangkangi ora serrata) melekat kuat di sini.', role: 'Batas mekanik dalam retina; jalur pelepasan pada vitrektomi (ILM peeling) dan titik traksi pada robekan.', clinical: 'Traksi vitreoretina di basis atau makula dapat merobek retina tepat di antarmuka ini → ablasi regmatogen.', sources: ['webvision', 'aveh-retina'] },
  { id: 'nfl', name: 'Lapis serabut saraf', latin: 'Stratum neurofibrarum', color: '#e8c88a', thickness: 'Akson RGC → diskus', description: 'Akson sel ganglion berjalan paralel di permukaan dalam menuju diskus optikus; paling tebal di sekitar diskus. Arkade pembuluh retina sentral berjalan di dalam lapis ini.', role: 'Kabel kolektor: ~1,2–1,8 jt akson menuju otak. Ketebalannya (RNFL) adalah biomarker glaukoma pada OCT.', clinical: 'Defek berkas serabut (wedge defect) + perdarahan diskus = tanda glaukoma dini. Oklusi vena/cabang tampak sebagai perdarahan di lapis ini.', sources: ['webvision', 'aveh-retina', 'lamina'] },
  { id: 'gcl', name: 'Lapis sel ganglion', latin: 'Stratum ganglionare', color: '#e8a87e', thickness: '1 lapis perifer · berlapis di makula', description: 'Badan sel ganglion: selapis di perifer, bertumpuk beberapa lapis di makula (basis tajam penglihatan sentral). Di foveola tidak ada — tersibak ke tepi membentuk clivus.', role: 'Neuron output retina; di fovea satu ganglion melayani sesedikit ~5 fotoreseptor (vs ribuan di perifer).', clinical: 'Kompleks GCL–IPL menipis pada neuropati optik dan glaukoma;Whole-field loss menyusul kerusakan NFL.', sources: ['webvision', 'aveh-retina'] },
  { id: 'ipl', name: 'Lapis pleksiform dalam', latin: 'Stratum plexiforme internum', color: '#dfc39a', thickness: 'Sinaps bipolar–amakrin–ganglion', description: 'Jalinan sinaps sel bipolar dan amakrin ke dendrit ganglion. Sel amakrin memodulasi kontras, gerak, dan adaptasi terang/gelap.', role: 'Pra-pemrosesan: pusat/surround receptive field dibentuk di sini sebelum sinyal keluar.', clinical: 'Disorganisasi lapis dalam (DRIL) pada edema makula diabetik berkorelasi dengan visus buruk.', sources: ['webvision'] },
  { id: 'inl', name: 'Lapis nuklear dalam', latin: 'Stratum nucleare internum', color: '#d9b48f', thickness: 'Inti bipolar/horisontal/amakrin/Müller', description: 'Inti sel bipolar, horizontal, amakrin, dan Müller. Batas terdalam sirkulasi retina: kapiler retinal memasok sampai sekitar tengah lapis ini.', role: 'Stasiun relay vertikal (fotoreseptor→bipolar→ganglion) dan lateral (horizontal/amakrin).', clinical: 'Edema kistoid diabetik berkantung di INL/OPL; oklusi arteri → infark lapis dalam (pemutihan).', sources: ['webvision', 'aveh-retina'] },
  { id: 'opl', name: 'Lapis pleksiform luar', latin: 'Stratum plexiforme externum', color: '#d4a982', thickness: 'Sinaps fotoreseptor–bipolar', description: 'Terminal sinaptik batang/kerucut (spherule/pedicel) bersinaps ke bipolar dan horizontal. Di makula serabutnya berjalan miring sebagai serabut Henle.', role: 'Transfer + pemrosesan warna lawan (opponent) pertama; bintang makula (hard exudate) mengendap di serabut Henle.', clinical: 'Star figure di sekitar fovea menandai eksudat kronis lapisan Henle (hipertensi, neuroretinitis).', sources: ['webvision'] },
  { id: 'onl', name: 'Lapis nuklear luar', latin: 'Stratum nucleare externum', color: '#c99a72', thickness: 'Inti fotoreseptor · ~10 baris di foveola', description: 'Inti sel batang dan kerucut. Di foveola menumpuk ~10 baris inti kerucut murni — satu-satunya lapis nuklear yang tersisa di dasar cekungan.', role: 'Menopang populasi fotoreseptor terpadat; ketebalannya mencerminkan integritas fototransduksi.', clinical: 'Penipisan ONL + gangguan zona elipsoid pada OCT = kerusakan fotoreseptor (degenerasi, toksik, pasca-ablasi).', sources: ['webvision', 'aveh-retina'] },
  { id: 'pr', name: 'Fotoreseptor + ELM', latin: 'Stratum photosensorium', color: '#f0d060', thickness: 'Batang + kerucut · segmen luar', description: 'Segmen luar batang/kerucut (cakram membran opsin) tertanam di mikrovili RPE; ELM adalah tautan adherens dengan Müller. Kerucut foveola terkecil dan terpadat; fovea avaskular (FAZ) dan ditopang koriokapiler.', role: 'Fototransduksi: foton → sinyal saraf. RPE mendaur ulang vitamin A (retinoid) untuknya.', clinical: 'Retinitis pigmentosa menyerang batang dulu (buta malam, lapang menyempit); degenerasi makula menyerang kerucut sentral.', sources: ['webvision', 'aveh-retina'] },
  { id: 'rpe', name: 'Epitel pigmen retina', latin: 'Epithelium pigmentosum retinae', color: '#6b4a3a', thickness: 'Selapis · 4–6 jt sel', description: 'Selapis kuboid berpigmen dari ora serrata ke diskus; mikrovili apikal memeluk segmen luar fotoreseptor. Bersama endotel koriokapiler membentuk sawar darah-retina luar; membran basal + basal kapiler = membran Bruch.', role: 'Pompa subretinal, daur retinoid, fagositosis cakram usang, dan peredam cahaya nyasar (paling berpigmen di makula → warna gelap).', clinical: 'Lepasnya neurosensorik dari RPE = ablasi retina. Defek RPE → neovaskularisasi koroid; drusen menumpuk di Bruch seiring usia.', sources: ['webvision', 'aveh-retina'] },
  { id: 'bruch', name: 'Membran Bruch', latin: "Membrana Bruch", color: '#8a7a5e', thickness: 'Lamina basal ganda', description: 'Lembaran 5-lapis tipis: basal RPE + kolagen/elastin + basal koriokapiler. Jalan tukar nutrien–limbah antara RPE dan darah koroid; bukaannya di diskus (BMO) menjadi batas anatomis diskus.', role: 'Filter metabolik luar; integritasnya menahan invasi pembuluh koroid ke retina.', clinical: 'Penebalan/drusen → AMD; lakuer crack → perdarahan; BMO adalah landmark OCT untuk margin diskus dan area rim.', sources: ['aveh-retina', 'lamina'] },
  { id: 'fovea', name: 'Makula–fovea–foveola', latin: 'Macula · fovea · foveola', color: '#e0784a', thickness: '5,5 / 1,5 / 0,35 mm · 15°/5°/1°', description: 'Makula (xanthophyll, GCL berlapis) → fovea (cekungan 0,25 mm) → foveola (lantai 0,13 mm): hanya RPE+fotoreseptor+ELM+ONL+Henle+ILM. Tanpa pembuluh (mengandalkan koriokapiler) agar cahaya tak terhalang.', role: 'Penglihatan sentral fotopik dan warna; kerucut terkecil-terpadat memberi akuitas tertinggi.', clinical: 'Lubang makula, edema, dan membran epiretina langsung mengancam visus sentral walau lesi kecil.', sources: ['aveh-retina', 'webvision'] },
  { id: 'ora-serrata', name: 'Ora serrata', latin: 'Ora serrata', color: '#9ab87e', thickness: '2,1 mm temporal · 0,7–0,8 nasal', description: 'Ujung bergerigi retina sensorik (±6 mm nasal / 7 mm temporal dari limbus; dentate processes + oral bays) yang beralih menjadi epitel nonpigmen pars plana. Basis vitreus 3–4 mm mengangkanginya dengan perlekatan terkuat.', role: 'Batas anterior retina fungsional sekaligus zona jangkar vitreus; rujukan posisi port bedah dan buckle.', clinical: 'Avulsi/trauma tumpul merobek basis–ora → dialisis retina. Granular tissue dan enclosed bay di sini mudah disangka lubang.', sources: ['aveh-retina', 'webvision'] },
];

// +X anterior (permukaan diskus), −X posterior (saraf). Diskus oval ±2×1,5 mm
// (±3 mm²), nasal-superior ±4–5 mm (rerata 4,76) dari fovea; ~1,2–1,8 jt akson
// tak bermielin sampai lewat lamina; trunk vaskular di kuadran nasal-atas.
export const onhStructures: MicroLayer[] = [
  { id: 'disc', name: 'Diskus optikus', latin: 'Discus nervi optici', color: '#f6c99d', thickness: 'Oval ±2×1,5 mm · tanpa fotoreseptor', description: 'Kepala saraf tempat akson RGC keluar bola mata; tanpa fotoreseptor sehingga menjadi blind spot fisiologis. Batasnya secara OCT adalah bukaan membran Bruch (BMO).', role: 'Pintu keluar ~1,2–1,8 jt akson menuju otak; posisinya nasal-superior ±4–5 mm dari fovea menjaga lapang sentral.', clinical: 'Ukuran diskus memengaruhi interpretasi cup: diskus besar dapat ber-cup besar secara fisiologis.', sources: ['cn2', 'aveh-retina'] },
  { id: 'cup', name: 'Cup optik', latin: 'Excavatio disci', color: '#f2e3c8', thickness: 'Depresi sentral · rasio c/d', description: 'Cekungan sentral tempat pembuluh sentral menembus; dindingnya adalah serabut yang berbelok 90° menukik ke lamina. Pada glaukoma cekungan melebar–mendalam (ekskavasi).', role: 'Ruang sisa setelah serabut mengisi rim; rasio cup/disc vertikal adalah metrik skrining utama.', clinical: 'Cupping glaukomatosa = kehilangan akson + remodeling/thinning posterior lamina; bedakan dari cupping non-glaukomatosa yang lebih pucat dan dangkal.', sources: ['lamina', 'aveh-retina'] },
  { id: 'rim', name: 'Neuroretinal rim', latin: 'Limbus neuroretinalis', color: '#e8a06a', thickness: 'Aturan ISNT', description: 'Cincin jaringan serabut antara margin diskus dan cup: normalnya Inferior > Superior > Nasal > Temporal. Penipisan dini predominan temporal-inferior lalu temporal-superior (notch), sisa akhir di nasal.', role: 'Cadangan akson yang terlihat; luas dan warnanya menilai kesehatan saraf.', clinical: 'Notch rim + perdarahan diskus + defek lapang setempat = trias glaukoma. Pallor menonjol tanpa ekskavasi mengarah ke atrofi non-glaukomatosa.', sources: ['lamina'] },
  { id: 'lamina', name: 'Lamina kribrosa', latin: 'Lamina cribrosa sclerae', color: '#cbb89a', thickness: 'Anyaman berfenestrasi', description: 'Lempeng-lempeng kolagen-elastin berpori (isi astrosit + kapiler) tempat akson + trunk vaskular lewat; berjangkar ke sklera peripapiler. Dasar cup di permukaan dalam, menghadap cairan serebrospinal di permukaan luar.', role: 'Penopang mekanik + jendela nutrisi akson; gradien tekanan trans-lamina (TIO vs intrakranial) bekerja di sini.', clinical: 'Defek fokal/pembesaran pori + penipisan posterior = glaukoma; terlihat lebih baik dengan EDI/SS-OCT daripada foto.', sources: ['lamina', 'cn2'] },
  { id: 'rnfl', name: 'Serabut prapapiler', latin: 'Neurofibrae prelaminares', color: '#e8c88a', thickness: 'Belokan 90° ke lamina', description: 'Akson NFL berbelok tajam menukik ke pori lamina; serabut perifer berliku lebih serpentine daripada sentral sehingga rentan pada gradien tekanan tepi diskus.', role: 'Segmen transisi retina→saraf; ketebalan peripapilernya adalah target OCT struktural.', clinical: 'Penipisan sektoral RNFL mendahului defek lapang; perdarahan flame di sini menandai progresi.', sources: ['lamina', 'cn2'] },
  { id: 'vessels', name: 'Trunk vaskular sentral', latin: 'A./V. centralis retinae', color: '#c0392b', thickness: 'Trunk nasal-atas', description: 'Arteri–vena sentral menembus lamina (biasanya kuadran nasal-atas dekat lamina) lalu berarkade di NFL. Bayangan pembuluh menjadi patokan fiksasi OCT dan foto serial.', role: 'Satu-satunya suplai dalam retina; pulsasi vena spontan menandakan tekanan intrakranial tidak kritis.', clinical: 'Oklusi (CRAO/BRAO, CRVO/BRVO) memberi pola iskemia/perdarahan sesuai teritori; nasal displacement trunk = tanda remodeling glaukomatosa.', sources: ['cn2', 'aveh-retina'] },
  { id: 'bmo', name: 'Bukaan Bruch (BMO)', latin: 'Apertura membranae Bruch', color: '#8a7a5e', thickness: 'Margin diskus OCT', description: 'Tepi akhir membran Bruch/RPE mengelilingi kanal neural; garis penghubung antar tepi BMO menjadi bidang rujukan pengukuran rim (BMO-MRW) pada OCT.', role: 'Batas anatomis diskus yang reprodusibel antar pemeriksa dan antar kunjungan.', clinical: 'Rim berbasis BMO lebih sensitif daripada estimasi klinis cup/disc untuk glaukoma dini dan miopia.', sources: ['lamina'] },
];
