import type {Structure, StructureId, OrbitalStructureId} from './types';

const data: [OrbitalStructureId,string,string,string,string,string,string][] = [
 ['conjunctiva','Konjungtiva','Tunica conjunctiva','Selubung & orbita','#dba8a8','Mukosa permukaan sklera anterior yang berbalik di forniks menuju sisi dalam kelopak. Kornea tetap terbuka.','Membentuk kantong konjungtiva; berbeda dari kapsul Tenon di bawahnya.'],
 ['tenon','Kapsul Tenon','Fascia bulbi','Selubung & orbita','#c9d7ca','Selubung fasia di luar sklera, dari sekitar saraf optik menuju limbus.','Menjadi selubung gerak globe, berhubungan dengan fasia otot ekstraokular.'],
 ['orbital-fat','Lemak orbita','Corpus adiposum orbitae','Selubung & orbita','#e4c878','Jaringan lemak di dalam dan di luar kerucut otot rektus.','Bantalan jaringan lunak di antara globe, otot, dan dinding orbita.'],
 ['orbital-bone','Dinding orbita','Parietes orbitae','Selubung & orbita','#d1c5ac','Rongga tulang dengan apertura anterior dan apeks posterior.','Atap, dasar, dinding medial, dan lateral ditampilkan sebagai selubung; sutura dan foramen tidak diperinci.'],
 ['rectus-superior','Rektus superior','M. rectus superior','Otot ekstraokular','#ce7771','Otot dari apeks orbita ke sklera superior, di bawah levator.','Aksi utama elevasi; juga intorsi dan adduksi. Persarafan CN III.'],
 ['rectus-inferior','Rektus inferior','M. rectus inferior','Otot ekstraokular','#c97b67','Otot dari apeks orbita ke sklera inferior.','Aksi utama depresi; juga ekstorsi dan adduksi. Persarafan CN III.'],
 ['rectus-medial','Rektus medial','M. rectus medialis','Otot ekstraokular','#cd8b8f','Otot rektus pada sisi nasal globe.','Adduksi. Persarafan CN III.'],
 ['rectus-lateral','Rektus lateral','M. rectus lateralis','Otot ekstraokular','#bf697d','Otot rektus pada sisi temporal globe.','Abduksi. Persarafan CN VI.'],
 ['oblique-superior','Oblik superior','M. obliquus superior','Otot ekstraokular','#d59881','Berjalan ke troklear superomedial lalu tendonnya berbalik ke sklera posterior superior.','Intorsi, depresi, dan abduksi; aksi bergantung posisi mata. Persarafan CN IV.'],
 ['oblique-inferior','Oblik inferior','M. obliquus inferior','Otot ekstraokular','#cf9a8d','Berasal dari dasar orbita anterior medial, melewati bawah globe menuju sklera posterolateral.','Ekstorsi, elevasi, dan abduksi. Berbeda dari rektus, tidak berasal dari cincin apeks. CN III.'],
 ['levator','Levator palpebra','M. levator palpebrae superioris','Kelopak','#b98c9c','Otot dari posterior orbita yang melintas di atas rektus superior menuju kelopak atas.','Mengangkat kelopak atas melalui aponeurosis. Persarafan CN III.'],
 ['upper-lid','Kelopak atas','Palpebra superior','Kelopak','#d19f86','Lipatan jaringan pelindung di anterior globe.','Permukaan palpebral menghadap kantong konjungtiva. Gerakan kedip membantu distribusi air mata.'],
 ['lower-lid','Kelopak bawah','Palpebra inferior','Kelopak','#d5aa91','Kelopak di bawah fisura palpebra dengan punctum di tepi medial.','Menopang meniskus air mata dan turut menjaga permukaan mata.'],
 ['lacrimal-gland','Kelenjar lakrimal','Glandula lacrimalis','Sistem lakrimal','#bb9ac8','Kelenjar di bagian superotemporal orbita.','Duktus ekskretorius menuju forniks superior lateral. Ini sumber air mata, bukan sumber aqueous.'],
 ['puncta','Puncta lakrimal','Puncta lacrimalia','Sistem lakrimal','#81d5de','Dua muara kecil pada tepi kelopak atas dan bawah dekat kantus medial.','Pintu masuk air mata dari permukaan ke kanalikuli. Diameter ditonjolkan agar tampak.'],
 ['canaliculi','Kanalikuli lakrimal','Canaliculi lacrimales','Sistem lakrimal','#83c6d7','Saluran atas dan bawah dengan bagian pendek vertikal, lalu menuju medial.','Pada pola yang ditampilkan, keduanya bersatu sebelum memasuki sakus. Variasi muara terpisah tidak ditampilkan.'],
 ['lacrimal-sac','Sakus lakrimal','Saccus lacrimalis','Sistem lakrimal','#91b7d4','Reservoir di fossa lakrimal pada sisi medial anterior orbita.','Menerima aliran dari kanalikuli dan berlanjut ke duktus nasolakrimal.'],
 ['nasolacrimal','Duktus nasolakrimal','Ductus nasolacrimalis','Sistem lakrimal','#87aee0','Saluran dari sakus menuju kavum nasi.','Bermuara di meatus inferior, di bawah konka inferior; ujung inferior saluran mewakili muara. Konka tidak dimodelkan.'],
];
export const orbitalStructures:Structure[]=data.map(([id,name,latin,group,color,description,relation])=>({id,name,latin,group,color,description,relation,function:relation,clinical:group==='Sistem lakrimal'?'Lokasi hambatan drainase dipelajari dengan mengikuti urutan puncta → kanalikuli → sakus → duktus. Model tidak menunjukkan hasil pemeriksaan patensi.':group==='Otot ekstraokular'?'Aksi otot bergantung arah pandang. Posisi model adalah primer; tidak mensimulasikan gaya, pulley jaringan lunak, atau pemeriksaan diplopia.':'Hubungan spasial membantu orientasi orbita. Selubung, tulang, dan jaringan kelopak tetap skematik; bukan panduan tindakan.',fact:group==='Sistem lakrimal'?'Air mata ≠ aqueous humor':group==='Otot ekstraokular'?'Posisi primer · aksi bukan simulasi gaya':'Konteks orbita · skematik',sources:group==='Sistem lakrimal'?['lacrimal-anatomy','lacrimal-drainage']:group==='Otot ekstraokular'?['eom-anatomy']:['orbit-anatomy']}));
export const orbitalIds=orbitalStructures.map(s=>s.id);
export const isOrbital=(id:StructureId)=>orbitalIds.includes(id);
